# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rover_pb2 as rover__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rover_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class roverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMap = channel.unary_unary(
                '/rover.rover/GetMap',
                request_serializer=rover__pb2.FileName.SerializeToString,
                response_deserializer=rover__pb2.Map.FromString,
                _registered_method=True)
        self.GetStreamCommands = channel.unary_stream(
                '/rover.rover/GetStreamCommands',
                request_serializer=rover__pb2.Api.SerializeToString,
                response_deserializer=rover__pb2.Commands.FromString,
                _registered_method=True)
        self.GetMine = channel.unary_unary(
                '/rover.rover/GetMine',
                request_serializer=rover__pb2.Mine_Number.SerializeToString,
                response_deserializer=rover__pb2.Mine.FromString,
                _registered_method=True)
        self.ListCommands = channel.unary_unary(
                '/rover.rover/ListCommands',
                request_serializer=rover__pb2.CommandSuccess.SerializeToString,
                response_deserializer=rover__pb2.Success.FromString,
                _registered_method=True)
        self.SharePin = channel.unary_unary(
                '/rover.rover/SharePin',
                request_serializer=rover__pb2.Index.SerializeToString,
                response_deserializer=rover__pb2.Pin.FromString,
                _registered_method=True)


class roverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SharePin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_roverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=rover__pb2.FileName.FromString,
                    response_serializer=rover__pb2.Map.SerializeToString,
            ),
            'GetStreamCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStreamCommands,
                    request_deserializer=rover__pb2.Api.FromString,
                    response_serializer=rover__pb2.Commands.SerializeToString,
            ),
            'GetMine': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMine,
                    request_deserializer=rover__pb2.Mine_Number.FromString,
                    response_serializer=rover__pb2.Mine.SerializeToString,
            ),
            'ListCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCommands,
                    request_deserializer=rover__pb2.CommandSuccess.FromString,
                    response_serializer=rover__pb2.Success.SerializeToString,
            ),
            'SharePin': grpc.unary_unary_rpc_method_handler(
                    servicer.SharePin,
                    request_deserializer=rover__pb2.Index.FromString,
                    response_serializer=rover__pb2.Pin.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rover.rover', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rover.rover', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class rover(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.rover/GetMap',
            rover__pb2.FileName.SerializeToString,
            rover__pb2.Map.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStreamCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rover.rover/GetStreamCommands',
            rover__pb2.Api.SerializeToString,
            rover__pb2.Commands.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.rover/GetMine',
            rover__pb2.Mine_Number.SerializeToString,
            rover__pb2.Mine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.rover/ListCommands',
            rover__pb2.CommandSuccess.SerializeToString,
            rover__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SharePin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.rover/SharePin',
            rover__pb2.Index.SerializeToString,
            rover__pb2.Pin.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
