# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rover.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rover.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brover.proto\x12\x05rover\"\x19\n\x08\x46ileName\x12\r\n\x05mapID\x18\x01 \x01(\t\"X\n\x03Map\x12\x17\n\x0bmap_display\x18\x01 \x01(\tB\x02\x18\x01\x12\x19\n\x11map_display_array\x18\x02 \x03(\t\x12\x0c\n\x04rows\x18\x03 \x01(\x05\x12\x0f\n\x07\x63olumns\x18\x04 \x01(\x05\"\x17\n\x03\x41pi\x12\x10\n\x08\x61pi_name\x18\x01 \x01(\t\"$\n\x08\x43ommands\x12\x18\n\x10\x63ommands_display\x18\x01 \x01(\t\":\n\x0bMine_Number\x12\x17\n\x0bmine_number\x18\x01 \x01(\tB\x02\x18\x01\x12\x12\n\nmine_index\x18\x02 \x01(\x05\"\x1b\n\x04Mine\x12\x13\n\x0bmine_serial\x18\x01 \x01(\t\"\x1f\n\x07Success\x12\x14\n\x0csuccess_rate\x18\x01 \x01(\t\"\x1d\n\x05Index\x12\x14\n\x0cindex_number\x18\x01 \x01(\t\"\x19\n\x03Pin\x12\x12\n\npin_number\x18\x01 \x01(\t\"!\n\x0e\x43ommandSuccess\x12\x0f\n\x07success\x18\x01 \x01(\t2\xf5\x01\n\x05rover\x12\'\n\x06GetMap\x12\x0f.rover.FileName\x1a\n.rover.Map\"\x00\x12\x34\n\x11GetStreamCommands\x12\n.rover.Api\x1a\x0f.rover.Commands\"\x00\x30\x01\x12,\n\x07GetMine\x12\x12.rover.Mine_Number\x1a\x0b.rover.Mine\"\x00\x12\x37\n\x0cListCommands\x12\x15.rover.CommandSuccess\x1a\x0e.rover.Success\"\x00\x12&\n\x08SharePin\x12\x0c.rover.Index\x1a\n.rover.Pin\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rover_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAP'].fields_by_name['map_display']._loaded_options = None
  _globals['_MAP'].fields_by_name['map_display']._serialized_options = b'\030\001'
  _globals['_MINE_NUMBER'].fields_by_name['mine_number']._loaded_options = None
  _globals['_MINE_NUMBER'].fields_by_name['mine_number']._serialized_options = b'\030\001'
  _globals['_FILENAME']._serialized_start=22
  _globals['_FILENAME']._serialized_end=47
  _globals['_MAP']._serialized_start=49
  _globals['_MAP']._serialized_end=137
  _globals['_API']._serialized_start=139
  _globals['_API']._serialized_end=162
  _globals['_COMMANDS']._serialized_start=164
  _globals['_COMMANDS']._serialized_end=200
  _globals['_MINE_NUMBER']._serialized_start=202
  _globals['_MINE_NUMBER']._serialized_end=260
  _globals['_MINE']._serialized_start=262
  _globals['_MINE']._serialized_end=289
  _globals['_SUCCESS']._serialized_start=291
  _globals['_SUCCESS']._serialized_end=322
  _globals['_INDEX']._serialized_start=324
  _globals['_INDEX']._serialized_end=353
  _globals['_PIN']._serialized_start=355
  _globals['_PIN']._serialized_end=380
  _globals['_COMMANDSUCCESS']._serialized_start=382
  _globals['_COMMANDSUCCESS']._serialized_end=415
  _globals['_ROVER']._serialized_start=418
  _globals['_ROVER']._serialized_end=663
# @@protoc_insertion_point(module_scope)
