# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rover.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rover.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brover.proto\x12\x05rover\"\x19\n\x03Pin\x12\x12\n\npin_number\x18\x01 \x01(\t\"\x1a\n\x07\x63onfirm\x12\x0f\n\x07\x63onfirm\x18\x01 \x01(\t\"\x19\n\x08\x46ileName\x12\r\n\x05mapID\x18\x01 \x01(\t\"?\n\x03Map\x12\x19\n\x11map_display_array\x18\x01 \x03(\t\x12\x0c\n\x04rows\x18\x02 \x01(\x05\x12\x0f\n\x07\x63olumns\x18\x03 \x01(\x05\"\x17\n\x03\x41pi\x12\x10\n\x08\x61pi_name\x18\x01 \x01(\t\"$\n\x08\x43ommands\x12\x18\n\x10\x63ommands_display\x18\x01 \x01(\t\"!\n\x0bMine_Number\x12\x12\n\nmine_index\x18\x01 \x01(\x05\"\x1b\n\x04Mine\x12\x13\n\x0bmine_serial\x18\x01 \x01(\t2\xbd\x01\n\x05rover\x12\'\n\x06GetMap\x12\x0f.rover.FileName\x1a\n.rover.Map\"\x00\x12\x34\n\x11GetStreamCommands\x12\n.rover.Api\x1a\x0f.rover.Commands\"\x00\x30\x01\x12,\n\x07GetMine\x12\x12.rover.Mine_Number\x1a\x0b.rover.Mine\"\x00\x12\'\n\x07\x44\x65\x66used\x12\n.rover.Pin\x1a\x0e.rover.confirm\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rover_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PIN']._serialized_start=22
  _globals['_PIN']._serialized_end=47
  _globals['_CONFIRM']._serialized_start=49
  _globals['_CONFIRM']._serialized_end=75
  _globals['_FILENAME']._serialized_start=77
  _globals['_FILENAME']._serialized_end=102
  _globals['_MAP']._serialized_start=104
  _globals['_MAP']._serialized_end=167
  _globals['_API']._serialized_start=169
  _globals['_API']._serialized_end=192
  _globals['_COMMANDS']._serialized_start=194
  _globals['_COMMANDS']._serialized_end=230
  _globals['_MINE_NUMBER']._serialized_start=232
  _globals['_MINE_NUMBER']._serialized_end=265
  _globals['_MINE']._serialized_start=267
  _globals['_MINE']._serialized_end=294
  _globals['_ROVER']._serialized_start=297
  _globals['_ROVER']._serialized_end=486
# @@protoc_insertion_point(module_scope)
